#!/usr/bin/env python3
"""Turn the extracted corpus into a findings repo.

    python build_findings.py --out ../trading-corpus-findings

Reads the research packages, writes a README, per-topic markdown reports and
the raw claim tables. Reproducible: re-running regenerates everything from the
packages, so the reports are never hand-edited artefacts that drift.
"""
from __future__ import annotations

import argparse
import collections
import csv
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import corpus  # noqa: E402

SOURCE_DIR = Path.home() / "yt_transcripts"


def deep_link(row):
    return f"[{row['timestamp']}]({row['url']})"


def write_readme(out: Path, rows: list, packages: list) -> None:
    videos = {r["video_id"] for r in rows}
    types = collections.Counter(r["type"] for r in rows)
    channels = collections.Counter(
        (p.get("video") or {}).get("channel", "?") for _, p in packages)
    minutes = sum(int((p.get("video") or {}).get("duration") or 0)
                  for _, p in packages) // 60

    lines = [
        "# Trading Corpus: Findings",
        "",
        "Structured claims extracted from trading education video, built to be",
        "queried rather than watched. Every claim carries the video, the exact",
        "second it came from, and a link back to it.",
        "",
        "**Private. Derived from paid mentorship material; do not redistribute.**",
        "",
        "## Scale",
        "",
        "| | |",
        "|---|---|",
        f"| Videos | {len(videos)} |",
        f"| Video analysed | {minutes:,} minutes |",
        f"| Claims | {len(rows):,} |",
        f"| Trading rules | {types.get('rule', 0):,} |",
        f"| Concept definitions | {types.get('concept_definition', 0):,} |",
        "",
        "## Sources",
        "",
        "| Channel | Videos |",
        "|---|---|",
    ]
    for name, n in channels.most_common():
        lines.append(f"| {name} | {n} |")

    lines += [
        "",
        "## Claim types",
        "",
        "| Type | Count |",
        "|---|---|",
    ]
    for name, n in types.most_common():
        lines.append(f"| `{name}` | {n:,} |")

    lines += [
        "",
        "## Reports",
        "",
        "- [`reports/concepts.md`](reports/concepts.md) — every concept with the",
        "  definitions given for it, and which videos teach it",
        "- [`reports/rules.md`](reports/rules.md) — every actionable rule, by source",
        "- [`reports/instruments.md`](reports/instruments.md) — instrument and",
        "  timeframe coverage",
        "- [`reports/sources.md`](reports/sources.md) — per-video index",
        "- [`reports/conflicts.md`](reports/conflicts.md) — where sources disagree",
        "",
        "## Data",
        "",
        "`data/claims.csv` and `data/claims.jsonl` hold one row per claim with",
        "full provenance: `video_id`, `title`, `channel`, `timestamp`, `seconds`,",
        "`type`, `claim`, `source`, `model`, `url`.",
        "",
        "```python",
        "import pandas as pd",
        "df = pd.read_csv('data/claims.csv')",
        "df[df.type == 'rule'].claim.tolist()",
        "```",
        "",
        "## Method",
        "",
        "Each video was analysed whole by a vision-language model reading the",
        "screen AND hearing the narration. Videos over 30 minutes were split into",
        "clipped windows and merged on absolute timestamps. The model filled a",
        "JSON schema directly, so no regular expression guessed structure out of",
        "prose. Values it could not read come back empty rather than as a",
        "placeholder.",
        "",
        "Tickers, timeframes and indicator names are normalised, so `BTC/USD`,",
        "`BINANCE:BTCUSD` and `btc-usd` are one instrument and `M15`, `15 min`",
        "and `15-minute` are one timeframe.",
        "",
        "Generated by `build_findings.py` in the yt-chart-scrape repo. Reports are",
        "regenerated from the packages, never hand-edited.",
        "",
        "## Caveat",
        "",
        "These claims are what the sources SAY, not what is true. A rule appearing",
        "here is evidence that someone taught it, nothing more. Every row links to",
        "the second it came from so any of it can be checked against the video.",
    ]
    (out / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_concepts(out: Path, rows: list) -> None:
    by_term: dict = collections.defaultdict(list)
    for r in rows:
        if not r["type"].startswith("concept"):
            continue
        by_term[corpus.subject_of(r["claim"]).strip().lower()].append(r)

    lines = ["# Concepts", "",
             f"{len(by_term)} distinct concepts, ordered by how often they are "
             "taught.", ""]
    for term, items in sorted(by_term.items(),
                              key=lambda kv: (-len(kv[1]), kv[0])):
        vids = {r["video_id"] for r in items}
        lines.append(f"## {term}")
        lines.append("")
        lines.append(f"*{len(items)} mentions across {len(vids)} video(s)*")
        lines.append("")
        seen = set()
        for r in items:
            meaning = corpus.value_of(r["claim"]).strip()
            if not meaning or meaning.lower() == term:
                continue
            key = meaning.lower()[:80]
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"- {meaning}  \n  {deep_link(r)} — {r['title'][:60]}")
        lines.append("")
    (out / "reports" / "concepts.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")


def write_rules(out: Path, rows: list) -> None:
    rules = [r for r in rows if r["type"] == "rule"]
    by_channel: dict = collections.defaultdict(list)
    for r in rules:
        by_channel[r["channel"] or "unknown"].append(r)

    lines = ["# Trading Rules", "",
             f"{len(rules):,} rules stated across the corpus. Each links to the "
             "second it was said.", ""]
    for channel, items in sorted(by_channel.items(),
                                 key=lambda kv: -len(kv[1])):
        lines.append(f"## {channel} ({len(items)} rules)")
        lines.append("")
        by_video: dict = collections.defaultdict(list)
        for r in items:
            by_video[r["title"]].append(r)
        for title, rs in by_video.items():
            lines.append(f"### {title}")
            lines.append("")
            for r in sorted(rs, key=lambda x: x["seconds"]):
                lines.append(f"- **{deep_link(r)}** {r['claim']}")
            lines.append("")
    (out / "reports" / "rules.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")


def write_instruments(out: Path, rows: list) -> None:
    inst = collections.Counter(
        corpus.normalize_ticker(corpus.value_of(r["claim"])) or "?"
        for r in rows if r["type"] == "instrument")
    tfs = collections.Counter(
        corpus.normalize_timeframe(corpus.value_of(r["claim"]))
        or corpus.value_of(r["claim"])
        for r in rows if r["type"] == "timeframe")
    pats = collections.Counter(r["claim"].lower()
                               for r in rows if r["type"] == "chart_pattern")

    lines = ["# Instruments, Timeframes, Patterns", "", "## Instruments", "",
             "| Instrument | Mentions |", "|---|---|"]
    for name, n in inst.most_common(40):
        lines.append(f"| {name} | {n} |")
    lines += ["", "## Timeframes", "", "| Timeframe | Mentions |", "|---|---|"]
    for name, n in tfs.most_common(30):
        lines.append(f"| {name} | {n} |")
    lines += ["", "## Chart patterns and structures", "",
              "| Pattern | Mentions |", "|---|---|"]
    for name, n in pats.most_common(60):
        lines.append(f"| {name} | {n} |")
    (out / "reports" / "instruments.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")


def write_sources(out: Path, rows: list, packages: list) -> None:
    per_video = collections.Counter(r["video_id"] for r in rows)
    lines = ["# Source Index", "", "| Video | Channel | Min | Claims | Coverage |",
             "|---|---|---|---|---|"]
    for path, pkg in sorted(
            packages,
            key=lambda kv: -per_video.get(
                (kv[1].get("video") or {}).get("id", ""), 0)):
        v = pkg.get("video") or {}
        vis = pkg.get("visual_extraction") or {}
        vid = v.get("id") or path.name.split("_")[0]
        title = (v.get("title") or vid)[:58].replace("|", "/")
        cov = vis.get("coverage_pct")
        cov_s = f"{cov}%" if cov else "-"
        lines.append(
            f"| [{title}](https://www.youtube.com/watch?v={vid}) "
            f"| {v.get('channel','?')[:22]} | {int(v.get('duration') or 0)//60} "
            f"| {per_video.get(vid, 0)} | {cov_s} |")
    (out / "reports" / "sources.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")


def write_conflicts(out: Path, rows: list) -> None:
    conflicts = corpus.find_conflicts(rows)
    lines = ["# Disagreements", "",
             "Where sources teach the same indicator with different settings.",
             "Not necessarily an error: genuine disagreement is the point of a",
             "corpus, and no single video can show it to you.", ""]
    if not conflicts:
        lines.append("_None found._")
    for subject, values in conflicts:
        lines.append(f"## {subject}")
        lines.append("")
        for value, vids in sorted(values.items()):
            lines.append(f"- **{value}** — {len(vids)} video(s): "
                         + ", ".join(f"`{v}`" for v in vids[:6]))
        lines.append("")
    (out / "reports" / "conflicts.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True, help="Findings repo directory")
    ap.add_argument("--dir", default=str(SOURCE_DIR), help="Packages folder")
    args = ap.parse_args()

    out = Path(args.out)
    (out / "reports").mkdir(parents=True, exist_ok=True)
    (out / "data").mkdir(parents=True, exist_ok=True)

    packages = corpus.load_packages(Path(args.dir))
    rows = corpus.claim_rows(packages)
    if not rows:
        print("no claims found", file=sys.stderr)
        return 1

    with open(out / "data" / "claims.csv", "w", newline="",
              encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    with open(out / "data" / "claims.jsonl", "w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r, ensure_ascii=False) + "\n")

    write_readme(out, rows, packages)
    write_concepts(out, rows)
    write_rules(out, rows)
    write_instruments(out, rows)
    write_sources(out, rows, packages)
    write_conflicts(out, rows)

    print(f"{len(rows):,} claims from {len(packages)} packages -> {out}")
    for p in sorted(out.rglob("*.md")) + sorted(out.rglob("*.csv")):
        print(f"  {p.relative_to(out)}  {p.stat().st_size // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
